/**
 * @file drivers/windows/dsusb/dsusb_bus_ioctl.h
 * @brief C-compatible IOCTL contract for the DSUSB bus driver.
 */
#pragma once

#include <ntddk.h>

#define DSUSB_BUS_VERSION 1u

#define DSUSB_BUS_IOCTL_BASE 0x900

#define IOCTL_DSUSB_GET_VERSION   CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_CREATE_DEVICE CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_DESTROY_DEVICE CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_UPDATE_STATE  CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_UPDATE_TOUCH  CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_UPDATE_MOTION CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DSUSB_UPDATE_BATTERY CTL_CODE(FILE_DEVICE_UNKNOWN, DSUSB_BUS_IOCTL_BASE + 0x06, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _DSUSB_VERSION_PACKET {
  ULONG Version;
} DSUSB_VERSION_PACKET, *PDSUSB_VERSION_PACKET;

typedef struct _DSUSB_CREATE_DEVICE_PACKET {
  ULONG Version;
  LONG GlobalIndex;
  UCHAR ClientRelativeIndex;
  UCHAR Type;
  USHORT Capabilities;
  ULONG SupportedButtons;
} DSUSB_CREATE_DEVICE_PACKET, *PDSUSB_CREATE_DEVICE_PACKET;

typedef struct _DSUSB_DESTROY_DEVICE_PACKET {
  ULONG Version;
  LONG GlobalIndex;
} DSUSB_DESTROY_DEVICE_PACKET, *PDSUSB_DESTROY_DEVICE_PACKET;

typedef struct _DSUSB_UPDATE_STATE_PACKET {
  ULONG Version;
  LONG GlobalIndex;
  ULONG ButtonFlags;
  UCHAR Lt;
  UCHAR Rt;
  SHORT LsX;
  SHORT LsY;
  SHORT RsX;
  SHORT RsY;
} DSUSB_UPDATE_STATE_PACKET, *PDSUSB_UPDATE_STATE_PACKET;

typedef struct _DSUSB_UPDATE_TOUCH_PACKET {
  ULONG Version;
  LONG GlobalIndex;
  UCHAR EventType;
  UCHAR Reserved[3];
  ULONG PointerId;
  FLOAT X;
  FLOAT Y;
  FLOAT Pressure;
} DSUSB_UPDATE_TOUCH_PACKET, *PDSUSB_UPDATE_TOUCH_PACKET;

typedef struct _DSUSB_UPDATE_MOTION_PACKET {
  ULONG Version;
  LONG GlobalIndex;
  UCHAR MotionType;
  UCHAR Reserved[3];
  FLOAT X;
  FLOAT Y;
  FLOAT Z;
} DSUSB_UPDATE_MOTION_PACKET, *PDSUSB_UPDATE_MOTION_PACKET;

typedef struct _DSUSB_UPDATE_BATTERY_PACKET {
  ULONG Version;
  LONG GlobalIndex;
  UCHAR State;
  UCHAR Percentage;
  UCHAR Reserved[2];
} DSUSB_UPDATE_BATTERY_PACKET, *PDSUSB_UPDATE_BATTERY_PACKET;
